version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/sentinel"
    schedule:
      interval: "yearly"
# c2e-touch 6f1e8d3c
